#pragma once

#define SIZE_OF_ALPHABET 34

#define MIN_WORD_SIZE 2
#define MIN_CAPACITY_OF_REPLACMENTS 10
#define PAIR 2

#define OUTPUT_CURRENT_TEXT L'1'
#define FREQUENCY_ANALYSIS L'2'
#define MAKE_REPLACE_IN_TEXT L'3'
#define UNDO L'4'
#define AUTO_REPLACEMENT L'5'
#define OUTPUT_LAST_REPLACEMENTS L'6'
#define DISPLAY_GROUPED L'7'
#define DISPLAY_GROUPED_UNSCRAMBLED L'8'
#define FLUSH L'9'
#define EXIT L'0'